name: Opret opgave
description: Indtast oplysninger for at få din opgave udleveret.
title: Opret Opgave
labels:
  - opgaver
body:
  - type: input
    id: github-username
    attributes:
      label: GitHub brugernavn
      description: Skriv dit brugernavn som du benytter når du logger på GitHub
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Navn
      description: Dit fulde navn
    validations:
      required: true
  - type: input
    id: class
    attributes:
      label: Hold
      description: Dit hold nummer
      placeholder: WU16, WU17
    validations:
      required: true
  - type: hidden
    id: template-repo
    attributes:
      label: template-repo
      # Navn på Template Repository
      value: test-opgave
  - type: hidden
    id: temaplate-owner
    attributes:
      label: template-owner
      # Navn på organisation hvor opgave-repoet bor
      value: webkollegiet-opgaver
